# Generated by Django 3.2.8 on 2021-10-22 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20211022_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='like_users',
            new_name='like',
        ),
    ]
